AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**/**
    # - config/**/**
    - script/**/**
Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - config/**/**
Metrics/LineLength:
  Max: 120
Rails:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
