# Global configuration options. The `queue_ahead` and `tz` options can also be set on each task.
queue_ahead: 360 # Number of minutes to queue jobs into the future
queue_name: 'default' # The Sidekiq queue name used by SimpleScheduler::FutureJob
tz: 'Europe/Paris' # The application time zone will be used by default if not set

notify_reservation_in_three_hours:
  class: 'NotifyReservationInThreeHoursJob'
  every: '1.hour'
  at: '*:00'
  expires_after: '3.hours'

notify_reservation_one_day_without_answer:
  class: 'NotifyReservationOneDayWithoutAnswerJob'
  every: '1.day'
  at: '14:00'
  expires_after: '23.hours'

notify_user_two_days_after_join:
  class: 'NotifyUserTwoDaysAfterJoinJob'
  every: '1.day'
  at: '14:00'
  expires_after: '23.hours'

notify_user_five_days_after_invite:
  class: 'NotifyUserFiveDaysAfterInviteJob'
  every: '1.day'
  at: '14:00'
  expires_after: '23.hours'

notify_user_ten_days_after_invite:
  class: 'NotifyUserTenDaysAfterInviteJob'
  every: '1.day'
  at: '14:00'
  expires_after: '23.hours'

notify_user_six_days_after_reservation:
  class: 'NotifyUserSixDaysAfterReservationJob'
  every: '1.day'
  at: '14:00'
  expires_after: '23.hours'

notify_cookoon_pending_for_missing_stripe_account:
  class: 'NotifyCookoonPendingForMissingStripeAccountJob'
  every: '1.day'
  at: '14:00'
  expires_after: '23.hours'

reservations_cleanup:
  class: 'ReservationsCleanupJob'
  every: '1.hour'
  at: '*:00'
