# Global configuration options. The `queue_ahead` and `tz` options can also be set on each task.
queue_ahead: 360 # Number of minutes to queue jobs into the future
queue_name: 'default' # The Sidekiq queue name used by SimpleScheduler::FutureJob
tz: 'Europe/Paris' # The application time zone will be used by default if not set

# Notify reservation starting in 3 hours
notify_reservation_in_three_hours:
  class: 'NotifyReservationInThreeHoursJob'
  every: '1.hours'
  at: '*:00'
  expires_after: '3.hours'

notify_user_two_days_after_join:
  class: 'NotifyUserTwoDaysAfterJoinJob'
  every: '1.days'
  at: '14:00'
  expires_after: '23.hours'

notify_user_five_days_after_invite:
  class: 'NotifyUserFiveDaysAfterInviteJob'
  every: '1.days'
  at: '14:00'
  expires_after: '23.hours'

notify_user_ten_days_after_invite:
  class: 'NotifyUserTenDaysAfterInviteJob'
  every: '1.days'
  at: '14:00'
  expires_after: '23.hours'

# # Runs once every 2 minutes
# simple_task:
#   class: "SomeActiveJob"
#   every: "2.minutes"
#
# # Runs once every day at 4:00 AM. The job will expire after 23 hours, which means the
# # job will not run if 23 hours passes (server downtime) before the job is actually run
# overnight_task:
#   class: "SomeSidekiqWorker"
#   every: "1.day"
#   at: "4:00"
#   expires_after: "23.hours"
#
# # Runs once every half hour, starting on the 30 min mark
# half_hour_task:
#   class: "HalfHourTask"
#   every: "30.minutes"
#   at: "*:30"
#
# # Runs once every week on Saturdays at 12:00 AM
# weekly_task:
#   class: "WeeklyJob"
#   every: "1.week"
#   at: "Sat 0:00"
#   tz: "America/New_York"
